version: '3.8'

services:
  rapidraw-desktop:
    build:
      context: .
      dockerfile: Dockerfile.remote-desktop
    container_name: rapidraw-remote-desktop
    ports:
      # Web-based access (recommended)
      - "6080:6080"
      # Direct VNC access (optional, for VNC clients)
      - "5901:5901"
    restart: unless-stopped
    environment:
      - VNC_RESOLUTION=1920x1080
      - VNC_COL_DEPTH=24
      # No password needed for noVNC with this setup
      - VNC_PW=no
    # For GPU acceleration on Jetson (optional - uncomment if needed)
    # runtime: nvidia
    # devices:
    #   - /dev/dri:/dev/dri
    # Better performance
    shm_size: '2gb'
    # Persistent storage
    volumes:
      # Store desktop settings and user data
      - rapidraw-home:/home/ai
      # Mount a host directory for pictures (change the host path as needed)
      # Uncomment and modify the line below to use a specific host directory
      # - /path/to/your/pictures:/home/ai/Pictures
    # Resource limits (adjust based on your system)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

volumes:
  rapidraw-home:
    driver: local
