version: '3.8'

services:
  rapidraw:
    image: rapidraw:arm64
    container_name: rapidraw
    restart: unless-stopped
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    privileged: true
    runtime: nvidia
