version: '3.8'

services:
  rapidraw:
    build:
      context: .
      dockerfile: Dockerfile.cuda
      args:
        DOCKER_BUILDKIT: 1
    image: rapidraw-cuda:latest
    container_name: rapidraw-cuda
    runtime: nvidia
    restart: unless-stopped
    
    ports:
      # Web browser access
      - "6080:6080"
      # VNC client access
      - "5901:5901"
    
    # Shared memory for GPU operations
    shm_size: '2gb'
    
    environment:
      # GPU settings
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CUDA_VISIBLE_DEVICES=0
      # Display settings
      - DISPLAY=:1
      - VNC_RESOLUTION=1920x1080
      - VNC_COL_DEPTH=24
      # Performance
      - WGPU_BACKEND=vulkan
    
    volumes:
      # Persistent user home
      - rapidraw-home:/home/ai
      # Separate volume for pictures
      - rapidraw-pictures:/home/ai/Pictures
      # Optional: Mount host directory for importing photos
      # - /path/to/your/photos:/home/ai/Pictures/Import:ro
    
    # GPU device access for Jetson
    devices:
      - /dev/nvhost-ctrl
      - /dev/nvhost-ctrl-gpu
      - /dev/nvhost-prof-gpu
      - /dev/nvmap
      - /dev/nvhost-gpu
      - /dev/nvhost-as-gpu
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 32G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  rapidraw-home:
    driver: local
  rapidraw-pictures:
    driver: local
