version: '3.8'

services:
  rapidraw:
    build:
      context: .
      dockerfile: Dockerfile.arm64
    image: rapidraw:arm64
    container_name: rapidraw
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      # X11 socket for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Wayland socket (if using Wayland)
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
      # GPU access for NVIDIA Jetson
      - /dev/nvhost-ctrl:/dev/nvhost-ctrl
      - /dev/nvhost-ctrl-gpu:/dev/nvhost-ctrl-gpu
      - /dev/nvhost-prof-gpu:/dev/nvhost-prof-gpu
      - /dev/nvmap:/dev/nvmap
      - /dev/nvhost-gpu:/dev/nvhost-gpu
      - /dev/nvhost-as-gpu:/dev/nvhost-as-gpu
    devices:
      # GPU devices
      - /dev/nvhost-ctrl
      - /dev/nvhost-ctrl-gpu
      - /dev/nvhost-prof-gpu
      - /dev/nvmap
      - /dev/nvhost-gpu
      - /dev/nvhost-as-gpu
    runtime: nvidia
    network_mode: host
    privileged: true
